[package]
name = "scripts"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
async-recursion = "1.1.1"
chrono = "0.4.45"
envy = "0.4.2"
flate2 = "1.1.9"
futures-util = "0.3.33"
serde = "1.0.229"
serde_json = "1.0.151"
solana-account-decoder = "3.1.14"
solana-client = "3.1.14"
solana-sdk = "4.1.0"
solana-system-interface = { version = "3.3.0", features = ["bincode"] }
spl-associated-token-account-interface = "2.0.0"
spl-token-2022-interface = "3.1.1"
spl-token-interface = "3.0.0"
spl-token-metadata-interface = "1.0.1"
tokio = "1.53.1"
url = { version = "2.5.8", features = ["serde"] }
